package pl.com.app.entity;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "shop_order")
public class Order extends Common {

    @Column(name = "order_number")
    private String autoGeneratedNumber;

    @Column(name = "order_date")
    private Date orderDate;

    @ManyToMany
    @JoinTable(name = "order_product",
        joinColumns = @JoinColumn(name = "order_id"),
        inverseJoinColumns = @JoinColumn(name = "product_id"))
    private Set<Product> products;

    @ManyToOne
    @JoinColumn(name = "client_id")
    private Client client;

    @ManyToOne
    @JoinColumn(name = "payment_type_dic_id")
    private Dictionary paymentType;

    public String getAutoGeneratedNumber() {
        return autoGeneratedNumber;
    }

    public void setAutoGeneratedNumber(String autoGeneratedNumber) {
        this.autoGeneratedNumber = autoGeneratedNumber;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Set<Product> getProducts() {
        return products;
    }

    public void setProducts(Set<Product> products) {
        this.products = products;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Dictionary getPaymentType() {
        return paymentType;
    }

    public void setPaymentType(Dictionary paymentType) {
        this.paymentType = paymentType;
    }

    public void addProduct(Product product){
        if(products == null){
            products = new HashSet<>();
        }
        products.add(product);
    }

}
