package pl.com.app.entity;

import java.util.Date;
import java.util.Set;

public class Order extends Common {

    private String autoGeneratedNumber;

    private Date orderDate;

    private Set<Product> products;

    private Client client;

    private Dictionary paymentType;

    public String getAutoGeneratedNumber() {
        return autoGeneratedNumber;
    }

    public void setAutoGeneratedNumber(String autoGeneratedNumber) {
        this.autoGeneratedNumber = autoGeneratedNumber;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Set<Product> getProducts() {
        return products;
    }

    public void setProducts(Set<Product> products) {
        this.products = products;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Dictionary getPaymentType() {
        return paymentType;
    }

    public void setPaymentType(Dictionary paymentType) {
        this.paymentType = paymentType;
    }
}
